<?php
// Include after config.php — needs the session already started.

function currentLang(): string {
    $lang = $_SESSION['lang'] ?? 'bn';
    return in_array($lang, ['bn', 'en'], true) ? $lang : 'bn';
}

function t(string $key): string {
    global $TRANSLATIONS;
    $lang = currentLang();
    return $TRANSLATIONS[$lang][$key] ?? $TRANSLATIONS['bn'][$key] ?? $key;
}

$TRANSLATIONS = [
'bn' => [
    // ---- brand / topbar ----
    'brand_title'        => 'ত্রাণ বিতরণ Duplicate Prevention System',
    'brand_sub'           => 'Relief Distribution & Fair Allocation Platform',
    'logout'              => 'লগআউট',
    'tab_distribute'       => 'ত্রাণ বিতরণ',
    'tab_register_family'  => 'পরিবার নিবন্ধন',
    'tab_dashboard'         => 'Fairness Dashboard',
    'tab_family_list'       => 'সব পরিবার',
    'tab_duplicate_log'     => 'Duplicate Log',
    'tab_stock'              => 'NGO Stock',
    'tab_profile'             => 'প্রোফাইল',

    // ---- login page ----
    'login_title'         => 'ত্রাণ বিতরণ সিস্টেম',
    'login_sub'            => 'Relief Distribution Duplicate Prevention',
    'brand_tagline'         => 'এক প্ল্যাটফর্মে বন্যা দুর্গতদের কাছে দ্রুত, স্বচ্ছ ও ডুপ্লিকেট-মুক্ত ত্রাণ পৌঁছে দিন।',
    'brand_headline_1'        => 'বাংলাদেশের নির্ভরযোগ্য',
    'brand_headline_2'         => 'ত্রাণ বিতরণ প্ল্যাটফর্ম',
    'stat_families'             => 'নিবন্ধিত পরিবার',
    'stat_distributions'         => 'সফল বিতরণ',
    'stat_zones'                  => 'সক্রিয় ত্রাণ অঞ্চল',
    'scroll_hint'                   => 'আরও দেখুন',

    // ---- landing page: how it works ----
    'steps_eyebrow'    => 'প্রসেস',
    'steps_title'        => 'কীভাবে কাজ করে',
    'steps_sub'            => 'রেজিস্ট্রেশন থেকে ট্র্যাকিং পর্যন্ত — চারটা ধাপে পুরো প্রসেস।',
    'step1_title'           => 'নিবন্ধন করুন',
    'step1_desc'             => 'পরিবার প্রধানের NID ও সদস্যদের তথ্য দিয়ে নিবন্ধন করুন।',
    'step2_title'             => 'স্বয়ংক্রিয় যাচাই',
    'step2_desc'               => 'সিস্টেম নিজে থেকেই চেক করে কেউ আগে থেকে নিবন্ধিত কিনা।',
    'step3_title'               => 'ত্রাণ বিতরণ',
    'step3_desc'                 => 'NGO নির্দিষ্ট পরিবারকে ত্রাণ দেয় — ডুপ্লিকেট হলে block হয়ে যায়।',
    'step4_title'                 => 'ন্যায্য বণ্টন ট্র্যাকিং',
    'step4_desc'                   => 'কোন এলাকা কম পেয়েছে, লাইভ ড্যাশবোর্ডে দেখা যায়।',

    // ---- landing page: features ----
    'features_eyebrow'  => 'ফিচার',
    'features_title'      => 'এক প্ল্যাটফর্মে সব সমাধান',
    'features_sub'          => 'ডাটাবেস-লেভেল নিরাপত্তা থেকে শুরু করে রিয়েল-টাইম রিপোর্টিং — সবকিছু এক জায়গায়।',
    'feature1_title'         => 'Duplicate Prevention',
    'feature1_desc'           => 'SHA-256 hash ও DB trigger দিয়ে একই মানুষ (head বা member হিসেবে) দুইবার নিবন্ধিত হতে পারে না।',
    'feature2_title'           => 'Fair Allocation Map',
    'feature2_desc'             => 'জনসংখ্যা-অনুপাতে কোন এলাকা কম ত্রাণ পেয়েছে, সরাসরি মানচিত্রে দেখুন।',
    'feature3_title'             => 'Stock Tracking',
    'feature3_desc'               => 'প্রতিটা NGO-র হাতে কোন আইটেম কত আছে, রিয়েল-টাইমে ট্র্যাক হয়।',
    'feature4_title'               => 'Full Audit Trail',
    'feature4_desc'                 => 'প্রতিটা lookup আর blocked attempt লগ হয়ে থাকে — accountability নিশ্চিত।',

    // ---- landing page: showcase ----
    'showcase_title'    => 'একটা NID দিলেই — বাকিটা সিস্টেমের কাজ',
    'showcase_desc'       => 'অপারেটর শুধু NID/জন্ম নিবন্ধন নম্বর টাইপ করবে — পরিবার খোঁজা, ডুপ্লিকেট চেক করা, আর লগ রাখা, সবকিছু ব্যাকগ্রাউন্ডে স্বয়ংক্রিয়ভাবে হয়ে যায়।',
    'showcase_point1'       => 'Head বা যেকোনো সদস্যের NID দিয়েই পরিবার খুঁজে পাওয়া যায়',
    'showcase_point2'         => 'গত ৭ দিনে একই category-র ত্রাণ পেয়ে থাকলে সাথে সাথে সতর্ক করে',
    'showcase_point3'           => 'NGO-র স্টক অনুযায়ী বিতরণ automatically নিয়ন্ত্রিত হয়',
    'showcase_point4'             => 'plain NID কখনো সংরক্ষিত হয় না — শুধু SHA-256 hash',

    // ---- landing page: impact strip ----
    'impact_eyebrow'    => 'ইমপ্যাক্ট',
    'impact_title'        => 'সংখ্যায় আমাদের কার্যক্রম',
    'impact_sub'            => 'লাইভ ডাটাবেস থেকে সরাসরি — কোনো বানানো সংখ্যা নয়।',
    'impact_stat_ngo'         => 'সক্রিয় NGO',

    // ---- landing page: trust band ----
    'trust_eyebrow'     => 'নিরাপত্তা',
    'trust_title'         => 'ভরসাযোগ্য প্রযুক্তির উপর তৈরি',
    'trust_item1'           => 'SHA-256 এনক্রিপ্টেড ডেটা',
    'trust_item2'             => 'রিয়েল-টাইম ডুপ্লিকেট ব্লকিং',
    'trust_item3'               => 'সম্পূর্ণ Audit Trail',
    'trust_item4'                 => 'MySQL Trigger-ভিত্তিক নিরাপত্তা',
    'trust_item5'                   => 'Role-based Access Control',
    'trust_item6'                     => 'ইমেইল-ভেরিফায়েড NGO নিবন্ধন',

    // ---- landing page: testimonials ----
    'testimonials_eyebrow'  => 'অভিজ্ঞতা',
    'testimonials_title'      => 'যারা প্রতিদিন ব্যবহার করেন',
    'testimonials_sub'          => 'মাঠ পর্যায়ের কাজে ReliefX কীভাবে সাহায্য করছে।',
    'testimonial1_quote'          => '“আগে একই পরিবার দুই-তিনবার ত্রাণ পেয়ে যেত, অন্য এলাকা বঞ্চিত হতো। এখন সিস্টেমই সাথে সাথে ধরে ফেলে।”',
    'testimonial1_name'             => 'রফিকুল ইসলাম',
    'testimonial1_role'              => 'ফিল্ড কোঅর্ডিনেটর, ত্রাণ কার্যক্রম',
    'testimonial2_quote'                => '“ফেয়ারনেস ম্যাপ দেখে সাথে সাথে বোঝা যায় কোন এলাকায় বেশি জোর দিতে হবে। সিদ্ধান্ত নেওয়া অনেক সহজ হয়ে গেছে।”',
    'testimonial2_name'                   => 'নাসরিন আক্তার',
    'testimonial2_role'                     => 'জেলা ত্রাণ কর্মকর্তা',
    'testimonial3_quote'                       => '“স্টক ফুরিয়ে গেলে সিস্টেম নিজেই বিতরণ আটকে দেয় — ভুল করে বেশি বিতরণ করার সুযোগই নেই।”',
    'testimonial3_name'                          => 'ইউনিয়ন পরিষদ চেয়ারম্যান',
    'testimonial3_role'                            => 'স্থানীয় সরকার প্রতিনিধি',

    // ---- landing page: FAQ ----
    'faq_eyebrow'       => 'প্রশ্নোত্তর',
    'faq_title'           => 'সচরাচর জিজ্ঞাসিত প্রশ্ন',
    'faq_sub'               => 'ReliefX নিয়ে সাধারণ কিছু প্রশ্নের উত্তর।',
    'faq1_q'                  => 'ডুপ্লিকেট প্রতিরোধ ঠিক কীভাবে কাজ করে?',
    'faq1_a'                    => 'প্রতিটা NID/জন্ম নিবন্ধন নম্বরের SHA-256 hash তৈরি হয় এবং ডাটাবেস ইউনিক কনস্ট্রেইন্ট + trigger দিয়ে একই মানুষ (head বা member হিসেবে) দুইবার নিবন্ধিত হওয়া আটকে দেয়।',
    'faq2_q'                      => 'আমার NID কি সরাসরি সংরক্ষিত হয়?',
    'faq2_a'                        => 'না। plain NID কখনোই ডাটাবেসে সংরক্ষিত হয় না — শুধু এর SHA-256 hash থাকে, যা থেকে আসল নম্বর ফিরে পাওয়া সম্ভব নয়।',
    'faq3_q'                          => 'নতুন NGO কীভাবে অ্যাকাউন্ট খুলবে?',
    'faq3_a'                            => 'অফিসিয়াল ইমেইল দিয়ে "নিবন্ধন করুন" পেজ থেকে আবেদন করুন — একটা ভেরিফিকেশন কোড ইমেইলে যাবে, সেটা দিয়ে অ্যাকাউন্ট সক্রিয় হবে।',
    'faq4_q'                              => 'Fairness ratio কীভাবে হিসাব হয়?',
    'faq4_a'                                => 'প্রতিটা এলাকার জনসংখ্যা-অনুপাতে যা পাওয়ার কথা, তার সাথে আসলে যা পেয়েছে তার অনুপাত — এই হিসাব MySQL-এর <code>v_area_fairness</code> VIEW থেকে রিয়েল-টাইমে আসে।',
    'faq5_q'                                  => 'একই পরিবার দুইবার ত্রাণ পেতে চাইলে কী হয়?',
    'faq5_a'                                    => '৭ দিনের মধ্যে একই category-র ত্রাণ দ্বিতীয়বার দেওয়ার চেষ্টা হলে procedure/trigger সেটা ব্লক করে দেয় এবং duplicate_log টেবিলে লিখে রাখে।',

    // ---- landing page: final CTA ----
    'cta_title'         => 'আপনার ফাউন্ডেশন যোগ দিতে প্রস্তুত?',
    'cta_sub'             => 'অফিসিয়াল ইমেইল দিয়ে কয়েক মিনিটেই নিবন্ধন করুন — ভেরিফিকেশনের পর সাথে সাথে ব্যবহার শুরু করতে পারবেন।',
    'cta_btn'               => 'ফাউন্ডেশন নিবন্ধন করুন',
    'cta_btn_secondary'       => 'আরও জানুন',

    'footer_tagline'    => 'বাংলাদেশের বন্যা দুর্গতদের জন্য স্বচ্ছ ও ডুপ্লিকেট-মুক্ত ত্রাণ ব্যবস্থাপনা।',
    'login_page_title'      => 'লগইন — ত্রাণ বিতরণ সিস্টেম',
    'username'             => 'ইউজারনেম',
    'password'              => 'পাসওয়ার্ড',
    'login_btn'              => 'লগইন করুন',
    'new_foundation'          => 'নতুন ফাউন্ডেশন?',
    'register_with_email'     => 'অফিসিয়াল ইমেইল দিয়ে নিবন্ধন করুন',
    'admin_account'            => 'এডমিন অ্যাকাউন্ট',
    'err_not_verified'          => 'আগে আপনার ইমেইল ভেরিফাই করুন — নিবন্ধনের সময় পাঠানো লিংকে ক্লিক করুন।',
    'err_bad_login'               => 'ভুল Username অথবা Password।',
    'forgot_pw_link'                => 'পাসওয়ার্ড ভুলে গেছেন?',

    // ---- forgot / reset password ----
    'forgot_pw_title'      => 'পাসওয়ার্ড রিসেট — ত্রাণ বিতরণ সিস্টেম',
    'forgot_pw_h1'            => 'পাসওয়ার্ড ভুলে গেছেন?',
    'forgot_pw_sub'             => 'আপনার অ্যাকাউন্টের ইমেইল দিন — একটা ৬-সংখ্যার রিসেট কোড পাঠানো হবে।',
    'forgot_pw_request_btn'       => 'রিসেট কোড পাঠান',
    'forgot_pw_sent_h1'             => '📧 কোড পাঠানো হয়েছে',
    'forgot_pw_sent_sub'              => 'যদি এই ইমেইল দিয়ে কোনো অ্যাকাউন্ট থেকে থাকে, একটা ৬-সংখ্যার কোড পাঠানো হয়েছে। ১ ঘণ্টার মধ্যে ব্যবহার করুন।',
    'enter_reset_code_btn'              => 'কোড লিখুন →',
    'reset_pw_h1'                          => 'নতুন পাসওয়ার্ড সেট করুন',
    'reset_pw_sub'                            => 'ইমেইলে পাঠানো কোড ও আপনার নতুন পাসওয়ার্ড লিখুন।',
    'reset_code_label'                          => 'রিসেট কোড',
    'new_password_label'                          => 'নতুন পাসওয়ার্ড',
    'reset_submit_btn'                              => 'পাসওয়ার্ড আপডেট করুন',
    'reset_ok_h1'                                     => '✅ পাসওয়ার্ড আপডেট হয়েছে',
    'reset_ok_sub'                                      => 'নতুন পাসওয়ার্ড দিয়ে এখন লগইন করতে পারবেন।',
    'reset_expired_h1'                                    => '⌛ কোডের মেয়াদ শেষ',
    'reset_expired_sub'                                     => 'এই রিসেট কোডের মেয়াদ শেষ হয়ে গেছে। আবার অনুরোধ করুন।',
    'request_again'                                           => 'আবার অনুরোধ করুন',
    'err_reset_invalid'                                         => 'ইমেইল বা কোডটি সঠিক নয় (অথবা ইতিমধ্যে ব্যবহার হয়ে গেছে)।',
    'err_mail_failed_generic'                                     => 'ইমেইল পাঠাতে সমস্যা হয়েছে। কিছুক্ষণ পর আবার চেষ্টা করুন।',

    // ---- dashboard ----
    'kpi_families'         => 'নিবন্ধিত পরিবার',
    'kpi_distributions'      => 'সফল বিতরণ',
    'kpi_blocked'             => 'Blocked Duplicate',
    'kpi_ngo'                  => 'সক্রিয় NGO',
    'fairness_h2'                => 'Fair Allocation — Area Fairness Gauge',
    'fairness_sub'                 => 'Fairness ratio = (আসলে যা পেয়েছে) ÷ (জনসংখ্যা-অনুপাতে যা পাওয়ার কথা)।',
    'population'                     => 'জনসংখ্যা',
    'received'                        => 'পেয়েছে',
    'expected'                          => 'প্রাপ্য',
    'fairness_note'                       => 'উলম্ব দাগটা ১.০× (ন্যায্য অংশ) নির্দেশ করে। লাল = ৫০%-এর কম পেয়েছে (priority), হলুদ = আংশিক, সবুজ = ন্যায্য বা বেশি।',
    'map_h2'                                 => 'ত্রাণ অঞ্চল মানচিত্র',
    'map_sub'                                   => 'বাংলাদেশের মানচিত্রে ৮টা সক্রিয় ত্রাণ অঞ্চল — রঙ fairness ratio অনুযায়ী, আকার জনসংখ্যা অনুযায়ী। মার্কারে ক্লিক করে বিস্তারিত দেখুন।',
    'legend_low'                                  => '৫০%-এর কম পেয়েছে',
    'legend_partial'                                => 'আংশিক পেয়েছে',
    'legend_fair'                                     => 'ন্যায্য বা বেশি',
    'fairness_val_label'                                => 'Fairness',
    'ngo_perf_h2'                            => 'NGO Performance',
    'ngo_perf_sub'                              => 'প্রতিটা NGO এখন পর্যন্ত মোট কতবার ত্রাণ বিতরণ করেছে।',
    'weekly_trend_h2'                              => 'সাপ্তাহিক Trend (গত ৮ সপ্তাহ)',
    'weekly_trend_sub'                                => 'সপ্তাহ অনুযায়ী মোট বিতরণ সংখ্যা — কোন সপ্তাহে চাহিদা বেড়েছে বোঝা যায়।',

    // ---- distribute page ----
    'distribute_h2'          => 'ত্রাণ বিতরণ এন্ট্রি',
    'distribute_sub'           => 'NID দিলেই hash করে পরিবার খোঁজা হবে — plain NID কখনো ডাটাবেসে সংরক্ষিত হয় না, শুধু SHA-256 hash।',
    'nid_number'                 => 'এনআইডি/জন্ম নিবন্ধন নম্বর',
    'relief_item'                  => 'ত্রাণ সামগ্রী',
    'ngo'                             => 'NGO',
    'ngo_locked_note'                  => 'আপনার NGO স্বয়ংক্রিয়ভাবে সেট — অন্য NGO-র হয়ে entry দেওয়া যাবে না।',
    'distribution_point'                 => 'বিতরণ পয়েন্ট',
    'add_point_toggle'                     => '+ নতুন Distribution Point যোগ করো',
    'quick_pick_label'                       => 'দ্রুত নির্বাচন — পরিচিত বিপদজনক এলাকা',
    'or_full_location'                         => 'অথবা সম্পূর্ণ ঠিকানা দিয়ে খুঁজুন (যেকোনো উপজেলা)',
    'point_name_label'                           => 'পয়েন্টের নাম',
    'point_name_placeholder'                       => 'যেমন: ইউনিয়ন পরিষদ মাঠ',
    'save_point_btn'                                 => 'পয়েন্ট সংরক্ষণ করো',
    'quantity'                             => 'পরিমাণ',
    'confirm_distribution_btn'               => 'ত্রাণ প্রদান নিশ্চিত করুন',
    'stock_indicator_none'                       => '❌ এই NGO-র কাছে এই আইটেমের কোনো স্টক নেই — বিতরণ করা যাবে না। আগে "NGO Stock" পেজ থেকে স্টক যোগ করুন।',
    'stock_indicator_available'                    => '✅ বর্তমান স্টক: %s %s',
    'stock_indicator_low'                          => '⚠️ কম স্টক — মাত্র %s %s বাকি (ন্যূনতম %s প্রয়োজন)। দ্রুত "NGO Stock" পেজ থেকে যোগ করুন।',
    'no_stock_suffix'                                => 'স্টক নেই',
    'recent_dist_all'                              => 'সাম্প্রতিক বিতরণ (সব NGO)',
    'recent_dist_mine'                               => 'আমার NGO-র বিতরণ ইতিহাস',
    'no_records_yet'                                   => 'এখনো কোনো রেকর্ড নেই।',
    'th_family'                                          => 'পরিবার',
    'th_item'                                              => 'আইটেম',
    'th_quantity'                                            => 'পরিমাণ',
    'th_date'                                                  => 'তারিখ',

    // ---- register family page ----
    'reg_family_h2'          => 'নতুন পরিবার নিবন্ধন',
    'reg_family_sub'           => 'নাম সেভ করার আগে fuzzy matching চালিয়ে দেখা হয় কাছাকাছি বানানের নাম আগে থেকে registered কিনা।',
    'head_name_label'             => 'পরিবার প্রধানের নাম',
    'phone_label'                   => 'ফোন নম্বর',
    'area_label'                      => 'এলাকা',
    'family_size_label'                 => 'পরিবারের সদস্য সংখ্যা (প্রধানসহ)',
    'other_members_label'                 => 'অন্যান্য সদস্যদের তথ্য — প্রত্যেকের নাম ও NID/জন্ম নিবন্ধন নম্বর',
    'home_address_label'                    => 'পরিবারের প্রকৃত ঠিকানা (বিভাগ / জেলা / উপজেলা)',
    'division_label'                          => 'বিভাগ',
    'district_field_label'                      => 'জেলা',
    'upazila_label'                                => 'উপজেলা',
    'select_placeholder'                             => '— নির্বাচন করুন —',
    'zone_matched'                                     => 'এই উপজেলা "%s" ত্রাণ অঞ্চলের অন্তর্ভুক্ত।',
    'zone_not_covered'                                   => '⚠ এই উপজেলায় বর্তমানে কোনো সক্রিয় ত্রাণ কার্যক্রম নেই — নিবন্ধন করা যাবে না।',
    'select_upazila_required'                              => 'বিভাগ, জেলা ও উপজেলা নির্বাচন করুন।',
    'register_btn'                          => 'নিবন্ধন করুন',
    'registered_families_h2'                  => 'নিবন্ধিত পরিবার',
    'admin_view_note'                           => 'Admin view — hash preview দেখা যাচ্ছে (শুধু demonstration-এর জন্য)।',
    'operator_view_note'                          => '🔒 NGO Operator role-এ পুরো তালিকা দেখা যায় না (privacy) — "ত্রাণ বিতরণ" পেজে গিয়ে একটা নির্দিষ্ট NID দিয়ে খুঁজুন।',
    'no_families_yet'                               => 'এখনো কোনো পরিবার নিবন্ধিত হয়নি।',
    'th_name'                                          => 'নাম',
    'th_members'                                         => 'সদস্য',
    'nid_hash_preview'                                     => 'NID Hash (preview)',
    'fuzzy_modal_title'                                      => '⚠ সম্ভাব্য ডুপ্লিকেট নাম পাওয়া গেছে',
    'cancel_btn'                                               => 'বাতিল করুন',
    'register_anyway_btn'                                        => 'তবুও নতুন করে নিবন্ধন করুন',
    'member_no'                                                    => 'সদস্য',
    'name_placeholder'                                               => 'নাম',
    'number_placeholder'                                               => 'নম্বর',
    'birth_certificate'                                                  => 'জন্ম নিবন্ধন',
    'child_id_note'                                                        => 'পরিবার প্রধান শিশু হলে NID-এর বদলে জন্ম নিবন্ধন নম্বর নির্বাচন করুন।',

    // ---- family list page ----
    'family_list_h2'          => 'সব নিবন্ধিত পরিবার',
    'family_list_sub'           => 'মোট {count} টি পরিবার নিবন্ধিত আছে। নতুন কেউ নিবন্ধন করলে পেজ রিফ্রেশ করলেই এখানে দেখা যাবে।',
    'th_id'                        => 'ID',
    'th_phone'                       => 'ফোন',
    'th_registered_at'                 => 'নিবন্ধনের সময়',

    // ---- duplicate log page ----
    'dup_log_sub'         => 'যখনই কোনো NGO একই পরিবারকে একই ক্যাটাগরির ত্রাণ ৭ দিনের মধ্যে দ্বিতীয়বার দিতে চেষ্টা করে, সিস্টেম স্বয়ংক্রিয়ভাবে সেটা ব্লক করে এখানে লগ করে — গোপনীয়তার জন্য NID নয়, শুধু এর hash সংরক্ষিত হয়।',
    'dup_log_empty'         => 'এখনো কোনো duplicate attempt block হয়নি।',
    'th_attempted_ngo'        => 'যে NGO চেষ্টা করেছিল',
    'th_reason'                 => 'কারণ',
    'audit_h2'                    => 'Lookup Audit Trail',
    'audit_sub'                     => '"ত্রাণ বিতরণ" পেজে NID টাইপ করার সাথে সাথে যত লুকআপ হয়েছে তার সবগুলো এখানে — কোন NGO কার NID/জন্ম নিবন্ধন দিয়ে খুঁজেছে, আর সেটা কোন পরিবার/সদস্যের সাথে মিলেছে।',
    'audit_empty'                     => 'এখনো কোনো lookup হয়নি।',
    'audit_resolved_to'                 => 'যে পরিবার/সদস্যের সাথে মিলেছে',
    'audit_via_member'                    => 'সদস্য দিয়ে মিলেছে',
    'audit_via_head'                        => 'প্রধানের NID দিয়ে মিলেছে',

    // ---- register NGO page ----
    'ngo_reg_title'        => 'ফাউন্ডেশন নিবন্ধন — ত্রাণ বিতরণ সিস্টেম',
    'ngo_reg_h1'             => 'ফাউন্ডেশন নিবন্ধন',
    'ngo_reg_sub'              => 'অফিসিয়াল ইমেইল দিয়ে নতুন NGO অ্যাকাউন্ট খুলুন',
    'ngo_reg_success'           => '✅ নিবন্ধন সফল হয়েছে! %s ঠিকানায় একটা ৬-সংখ্যার ভেরিফিকেশন কোড পাঠানো হয়েছে। নিচের বাটনে ক্লিক করে কোডটি লিখুন।',
    'enter_code_btn'              => 'কোড লিখুন →',
    'ngo_name_label'              => 'ফাউন্ডেশন/NGO-র নাম',
    'reg_no_label'                  => 'রেজিস্ট্রেশন নম্বর',
    'contact_phone_label'             => 'যোগাযোগের ফোন',
    'official_email_label'              => 'অফিসিয়াল ইমেইল',
    'confirm_password_label'              => 'পাসওয়ার্ড নিশ্চিত করুন',
    'reg_stock_label'                          => 'প্রাথমিক স্টক (ঐচ্ছিক)',
    'reg_stock_sub'                              => 'আপনার প্রতিষ্ঠানের হাতে এখন যা স্টক আছে তা লিখুন — খালি রাখলে ০ ধরা হবে, পরে "NGO Stock" পেজ থেকেও যোগ করতে পারবেন।',
    'already_have_account'                  => 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    'err_required_fields'                     => 'সব প্রয়োজনীয় ফিল্ড পূরণ করুন।',
    'err_bad_email'                             => 'সঠিক অফিসিয়াল ইমেইল দিন।',
    'err_password_length'                         => 'পাসওয়ার্ড অন্তত ৬ ক্যারেক্টার হতে হবে।',
    'err_password_mismatch'                         => 'পাসওয়ার্ড দুটো মিলছে না।',
    'err_ngo_exists'                                  => 'এই ফাউন্ডেশনের নাম, রেজিস্ট্রেশন নম্বর বা ইমেইল দিয়ে ইতিমধ্যে নিবন্ধন আছে।',
    'err_user_exists'                                   => 'এই ইউজারনেম বা ইমেইল দিয়ে ইতিমধ্যে অ্যাকাউন্ট আছে।',
    'err_registration_failed'                             => 'নিবন্ধন ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'err_mail_failed'                                       => 'অ্যাকাউন্ট তৈরি হয়েছে কিন্তু ভেরিফিকেশন ইমেইল পাঠানো যায়নি: %s',

    // ---- verify email page ----
    'verify_title'        => 'ইমেইল ভেরিফিকেশন — ত্রাণ বিতরণ সিস্টেম',
    'verify_ok_h1'          => '✅ ভেরিফাই সম্পন্ন হয়েছে',
    'verify_ok_sub'           => 'আপনার অ্যাকাউন্ট এখন সক্রিয়। লগইন করতে পারবেন।',
    'go_to_login'               => 'লগইন পেজে যান',
    'verify_expired_h1'           => '⌛ কোডের মেয়াদ শেষ',
    'verify_expired_sub'            => 'এই ভেরিফিকেশন কোডের মেয়াদ শেষ হয়ে গেছে। আবার নিবন্ধন করুন — নতুন কোড পাবেন।',
    'register_again'                  => 'আবার নিবন্ধন করুন',
    'verify_form_h1'                     => 'আপনার কোডটি লিখুন',
    'verify_form_sub'                       => 'আপনার ইমেইলে পাঠানো ৬-সংখ্যার ভেরিফিকেশন কোডটি নিচে লিখুন।',
    'verify_code_label'                       => 'ভেরিফিকেশন কোড',
    'verify_submit_btn'                         => 'ভেরিফাই করুন',
    'err_verify_invalid'                          => 'ইমেইল বা কোডটি সঠিক নয় (অথবা ইতিমধ্যে ব্যবহার হয়ে গেছে)। আবার চেষ্টা করুন।',
    'verify_email_locked_note'                      => 'নিবন্ধনের সময় ব্যবহৃত ইমেইলটি এখানে লক করা আছে — পরিবর্তন করা যাবে না।',

    // ---- api / save_family.php ----
    'api_family_required'   => 'NID, নাম ও উপজেলা আবশ্যক।',
    'api_member_count_mismatch' => 'পরিবারের সদস্য সংখ্যা অনুযায়ী সবার তথ্য দিতে হবে।',
    'api_member_fields_required' => 'প্রত্যেক সদস্যের নাম, NID/জন্ম নিবন্ধন নম্বর ও ধরন আবশ্যক।',
    'api_family_saved'         => '"%s" ও পরিবারের %d জন সদস্য সফলভাবে নিবন্ধিত হয়েছে।',
    'api_member_dup'             => 'একজন সদস্যের NID/জন্ম নিবন্ধন নম্বর ইতিমধ্যে অন্য কোথাও নিবন্ধিত আছে।',
    'api_identity_conflict'         => 'এই NID/জন্ম নিবন্ধন নম্বর ইতিমধ্যে "%s" নামে family_id #%d-এ নিবন্ধিত আছে (প্রধান বা সদস্য হিসেবে) — একই মানুষ দুইবার নিবন্ধন করা যাবে না। ভুল হলে আগের রেকর্ডটা সংশোধন করুন।',
    'api_identity_conflict_db'        => 'এই NID/জন্ম নিবন্ধন নম্বর ইতিমধ্যে অন্য একটা পরিবারে (প্রধান বা সদস্য হিসেবে) নিবন্ধিত আছে — database নিজেই block করেছে।',
    'api_save_failed'              => 'সংরক্ষণ ব্যর্থ হয়েছে: %s',
    'api_dist_fields_required'       => 'সব ফিল্ড পূরণ করুন।',
    'api_point_required'               => 'পয়েন্টের নাম ও উপজেলা আবশ্যক।',
    'api_point_saved'                    => '"%s" পয়েন্ট সফলভাবে যোগ হয়েছে।',
    'api_csrf_invalid'                     => 'সেশনের মেয়াদ শেষ হয়ে গেছে বা ফর্মটি পুরনো — পেজ রিফ্রেশ করে আবার চেষ্টা করুন।',
    'api_session_expired'                    => 'আপনার সেশনের মেয়াদ শেষ হয়ে গেছে — আবার লগইন করুন।',

    // ---- stock page ----
    'stock_h2'        => 'NGO Stock ব্যবস্থাপনা',
    'stock_sub'         => 'প্রতিটা NGO-র হাতে কোন আইটেম কত পরিমাণ আছে তা এখানে দেখা যায়। ত্রাণ বিতরণের সময় স্বয়ংক্রিয়ভাবে এখান থেকে পরিমাণ বিয়োগ হয় — স্টক শূন্য হলে বিতরণ ব্লক হয়ে যাবে।',
    'stock_empty'         => 'কোনো stock রেকর্ড নেই।',
    'stock_available'      => 'বর্তমান স্টক',
    'stock_add'              => 'নতুন স্টক যোগ করুন',
    'stock_add_btn'            => 'যোগ করুন',
    'stock_note'                => 'প্রতিটা NGO-Item জোড়ার জন্য একটা ইউনিক স্টক রেকর্ড থাকে। "যোগ করুন" চাপলে বর্তমান পরিমাণের সাথে যোগ হয়, প্রতিস্থাপন হয় না।',
    'stock_added_msg'             => '%s একক স্টক যোগ হয়েছে।',

    // ---- profile page ----
    'profile_h2'                 => 'প্রোফাইল',
    'profile_sub'                  => 'আপনার প্রতিষ্ঠানের তথ্য ও লোগো এখান থেকে দেখুন ও হালনাগাদ করুন।',
    'admin_profile_note'             => 'এডমিন অ্যাকাউন্টের সাথে কোনো NGO যুক্ত নেই, তাই প্রোফাইল কাস্টমাইজেশন প্রযোজ্য নয়।',
    'profile_change_photo'              => 'ছবি পরিবর্তন করুন',
    'save_profile_btn'                    => 'সংরক্ষণ করুন',
    'profile_logo_note'                     => 'JPG, PNG বা WebP — সর্বোচ্চ ২MB। ছবিতে ক্লিক করে নতুন লোগো বেছে নিন, তারপর "সংরক্ষণ করুন" চাপুন।',
    'profile_saved_msg'                       => 'প্রোফাইল সফলভাবে হালনাগাদ হয়েছে।',
    'err_logo_upload'                           => 'ছবি আপলোড করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    'err_logo_too_large'                          => 'ছবির সাইজ ২MB-এর বেশি হতে পারবে না।',
    'err_logo_type'                                 => 'শুধু JPG, PNG বা WebP ছবি আপলোড করা যাবে।',
],
'en' => [
    'brand_title'        => 'Flood Relief Duplicate Prevention System',
    'brand_sub'           => 'Relief Distribution & Fair Allocation Platform',
    'logout'              => 'Logout',
    'tab_distribute'       => 'Relief Distribution',
    'tab_register_family'  => 'Family Registration',
    'tab_dashboard'         => 'Fairness Dashboard',
    'tab_family_list'       => 'All Families',
    'tab_duplicate_log'     => 'Duplicate Log',
    'tab_stock'              => 'NGO Stock',
    'tab_profile'             => 'Profile',

    'login_title'         => 'Relief Distribution System',
    'login_sub'            => 'Relief Distribution Duplicate Prevention',
    'brand_tagline'         => 'Deliver flood relief fast, transparently, and duplicate-free — all from one platform.',
    'brand_headline_1'        => "Bangladesh's Trusted",
    'brand_headline_2'         => 'Relief Distribution Platform',
    'stat_families'             => 'Registered Families',
    'stat_distributions'         => 'Successful Distributions',
    'stat_zones'                  => 'Active Relief Zones',
    'scroll_hint'                   => 'See more',

    // ---- landing page: how it works ----
    'steps_eyebrow'    => 'PROCESS',
    'steps_title'        => 'How It Works',
    'steps_sub'            => 'From registration to tracking — the whole process in four steps.',
    'step1_title'           => 'Register',
    'step1_desc'             => "Register with the family head's NID and every member's details.",
    'step2_title'             => 'Automatic Verification',
    'step2_desc'               => 'The system checks on its own whether anyone is already registered.',
    'step3_title'               => 'Relief Distribution',
    'step3_desc'                 => "NGOs give relief to the family — duplicates are blocked automatically.",
    'step4_title'                 => 'Fair Allocation Tracking',
    'step4_desc'                   => 'See which areas received less on the live dashboard.',

    // ---- landing page: features ----
    'features_eyebrow'  => 'FEATURES',
    'features_title'      => 'Everything In One Platform',
    'features_sub'          => 'From database-level security to real-time reporting — all in one place.',
    'feature1_title'         => 'Duplicate Prevention',
    'feature1_desc'           => 'SHA-256 hashing and DB triggers mean the same person (as head or member) can never register twice.',
    'feature2_title'           => 'Fair Allocation Map',
    'feature2_desc'             => 'See directly on a map which areas received less relief relative to population.',
    'feature3_title'             => 'Stock Tracking',
    'feature3_desc'               => "Track how much of each item every NGO has on hand, in real time.",
    'feature4_title'               => 'Full Audit Trail',
    'feature4_desc'                 => 'Every lookup and blocked attempt is logged — accountability guaranteed.',

    // ---- landing page: showcase ----
    'showcase_title'    => 'Just Enter an NID — The System Does the Rest',
    'showcase_desc'       => 'The operator just types an NID/Birth Certificate number — finding the family, checking for duplicates, and logging it all happens automatically in the background.',
    'showcase_point1'       => "Finds the family via the head's NID or any member's",
    'showcase_point2'         => 'Warns instantly if the same category was received in the last 7 days',
    'showcase_point3'           => "Distribution is automatically limited by the NGO's stock",
    'showcase_point4'             => 'The plain NID is never stored — only its SHA-256 hash',

    // ---- landing page: impact strip ----
    'impact_eyebrow'    => 'IMPACT',
    'impact_title'        => 'Our Impact In Numbers',
    'impact_sub'            => 'Straight from the live database — no invented figures.',
    'impact_stat_ngo'         => 'Active NGOs',

    // ---- landing page: trust band ----
    'trust_eyebrow'     => 'SECURITY',
    'trust_title'         => 'Built On Technology You Can Trust',
    'trust_item1'           => 'SHA-256 Encrypted Data',
    'trust_item2'             => 'Real-time Duplicate Blocking',
    'trust_item3'               => 'Full Audit Trail',
    'trust_item4'                 => 'MySQL Trigger-based Safety',
    'trust_item5'                   => 'Role-based Access Control',
    'trust_item6'                     => 'Email-verified NGO Registration',

    // ---- landing page: testimonials ----
    'testimonials_eyebrow'  => 'EXPERIENCE',
    'testimonials_title'      => 'Used In The Field, Every Day',
    'testimonials_sub'          => 'How ReliefX helps the people doing the actual distribution work.',
    'testimonial1_quote'          => '"Before, the same family could get relief two or three times while other areas went without. Now the system catches it instantly."',
    'testimonial1_name'             => 'Rafiqul Islam',
    'testimonial1_role'              => 'Field Coordinator, Relief Operations',
    'testimonial2_quote'                => '"The fairness map makes it immediately obvious which areas need more focus. Decisions are so much faster now."',
    'testimonial2_name'                   => 'Nasrin Akter',
    'testimonial2_role'                     => 'District Relief Officer',
    'testimonial3_quote'                       => '"Once stock runs out, the system blocks distribution on its own — there\'s no room for over-distributing by mistake."',
    'testimonial3_name'                          => 'Union Parishad Chairman',
    'testimonial3_role'                            => 'Local Government Representative',

    // ---- landing page: FAQ ----
    'faq_eyebrow'       => 'FAQ',
    'faq_title'           => 'Frequently Asked Questions',
    'faq_sub'               => 'Common questions about how ReliefX works.',
    'faq1_q'                  => 'How exactly does duplicate prevention work?',
    'faq1_a'                    => 'Every NID/Birth Certificate number is hashed with SHA-256, and a database unique constraint plus a trigger stop the same person (as head or member) from ever being registered twice.',
    'faq2_q'                      => 'Is my NID stored directly?',
    'faq2_a'                        => 'No. The plain NID is never stored in the database — only its SHA-256 hash, from which the original number cannot be recovered.',
    'faq3_q'                          => 'How does a new NGO open an account?',
    'faq3_a'                            => 'Apply from the "Register" page using your official email — a verification code is emailed to you, and entering it activates the account.',
    'faq4_q'                              => 'How is the fairness ratio calculated?',
    'faq4_a'                                => "It's the ratio of what an area actually received to what it should receive based on its population share — computed in real time from the MySQL <code>v_area_fairness</code> VIEW.",
    'faq5_q'                                  => 'What happens if the same family tries to get relief twice?',
    'faq5_a'                                    => 'If the same category is attempted again within 7 days, the procedure/trigger blocks it and logs the attempt in the duplicate_log table.',

    // ---- landing page: final CTA ----
    'cta_title'         => 'Ready To Bring Your Foundation On Board?',
    'cta_sub'             => 'Register with your official email in minutes — start using ReliefX right after verification.',
    'cta_btn'               => 'Register Your Foundation',
    'cta_btn_secondary'       => 'Learn More',

    'footer_tagline'    => "Transparent, duplicate-free relief management for Bangladesh's flood victims.",
    'login_page_title'      => 'Login — Relief Distribution System',
    'username'             => 'Username',
    'password'              => 'Password',
    'login_btn'              => 'Login',
    'new_foundation'          => 'New foundation?',
    'register_with_email'     => 'Register with your official email',
    'admin_account'            => 'Admin account',
    'err_not_verified'          => 'Please verify your email first — click the link sent at registration.',
    'err_bad_login'               => 'Incorrect username or password.',
    'forgot_pw_link'                => 'Forgot password?',

    // ---- forgot / reset password ----
    'forgot_pw_title'      => 'Reset Password — Relief Distribution System',
    'forgot_pw_h1'            => 'Forgot your password?',
    'forgot_pw_sub'             => 'Enter your account email — a 6-digit reset code will be sent to it.',
    'forgot_pw_request_btn'       => 'Send Reset Code',
    'forgot_pw_sent_h1'             => '📧 Code Sent',
    'forgot_pw_sent_sub'              => "If an account exists with this email, a 6-digit code has been sent. It's valid for 1 hour.",
    'enter_reset_code_btn'              => 'Enter Code →',
    'reset_pw_h1'                          => 'Set a New Password',
    'reset_pw_sub'                            => 'Enter the code emailed to you and your new password.',
    'reset_code_label'                          => 'Reset Code',
    'new_password_label'                          => 'New Password',
    'reset_submit_btn'                              => 'Update Password',
    'reset_ok_h1'                                     => '✅ Password Updated',
    'reset_ok_sub'                                      => 'You can now log in with your new password.',
    'reset_expired_h1'                                    => '⌛ Code Expired',
    'reset_expired_sub'                                     => 'This reset code has expired. Please request a new one.',
    'request_again'                                           => 'Request Again',
    'err_reset_invalid'                                         => 'That email or code is incorrect (or already used).',
    'err_mail_failed_generic'                                     => 'There was a problem sending the email. Please try again shortly.',

    'kpi_families'         => 'Registered Families',
    'kpi_distributions'      => 'Successful Distributions',
    'kpi_blocked'             => 'Blocked Duplicate',
    'kpi_ngo'                  => 'Active NGOs',
    'fairness_h2'                => 'Fair Allocation — Area Fairness Gauge',
    'fairness_sub'                 => 'Fairness ratio = (actually received) ÷ (share expected by population).',
    'population'                     => 'Population',
    'received'                        => 'Received',
    'expected'                          => 'Expected',
    'fairness_note'                       => 'The vertical line marks 1.0× (fair share). Red = received under 50% (priority), yellow = partial, green = fair or above.',
    'map_h2'                                 => 'Relief Zone Map',
    'map_sub'                                   => "The 8 active relief zones on the map of Bangladesh — color shows fairness ratio, size shows population. Click a marker for details.",
    'legend_low'                                  => 'Received under 50%',
    'legend_partial'                                => 'Partially received',
    'legend_fair'                                     => 'Fair or above',
    'fairness_val_label'                                => 'Fairness',
    'ngo_perf_h2'                            => 'NGO Performance',
    'ngo_perf_sub'                              => 'How many times each NGO has distributed relief so far.',
    'weekly_trend_h2'                              => 'Weekly Trend (last 8 weeks)',
    'weekly_trend_sub'                                => 'Total distributions per week — shows which weeks saw the most demand.',

    'distribute_h2'          => 'Relief Distribution Entry',
    'distribute_sub'           => 'Entering an NID looks up the family by hash — the plain NID is never stored in the database, only the SHA-256 hash.',
    'nid_number'                 => 'NID Number',
    'relief_item'                  => 'Relief Item',
    'ngo'                             => 'NGO',
    'ngo_locked_note'                  => 'Your NGO is set automatically — you cannot submit entries on behalf of another NGO.',
    'distribution_point'                 => 'Distribution Point',
    'add_point_toggle'                     => '+ Add New Distribution Point',
    'quick_pick_label'                       => 'Quick pick — known danger zones',
    'or_full_location'                         => 'Or search by full address (any upazila)',
    'point_name_label'                           => 'Point Name',
    'point_name_placeholder'                       => 'e.g. Union Parishad Field',
    'save_point_btn'                                 => 'Save Point',
    'quantity'                             => 'Quantity',
    'confirm_distribution_btn'               => 'Confirm Relief Distribution',
    'stock_indicator_none'                       => '❌ This NGO has no stock of this item — distribution isn\'t possible. Add stock from the "NGO Stock" page first.',
    'stock_indicator_available'                    => '✅ Current stock: %s %s',
    'stock_indicator_low'                          => '⚠️ Low stock — only %s %s left (minimum %s required). Add more from the "NGO Stock" page soon.',
    'no_stock_suffix'                                => 'no stock',
    'recent_dist_all'                              => 'Recent Distributions (All NGOs)',
    'recent_dist_mine'                               => "My NGO's Distribution History",
    'no_records_yet'                                   => 'No records yet.',
    'th_family'                                          => 'Family',
    'th_item'                                              => 'Item',
    'th_quantity'                                            => 'Quantity',
    'th_date'                                                  => 'Date',

    'reg_family_h2'          => 'New Family Registration',
    'reg_family_sub'           => 'Before saving the name, fuzzy matching checks whether a similarly-spelled name is already registered.',
    'head_name_label'             => "Family Head's Name",
    'phone_label'                   => 'Phone Number',
    'area_label'                      => 'Area',
    'family_size_label'                 => 'Number of Family Members (incl. head)',
    'other_members_label'                 => "Other Members' Info — name & NID/Birth Certificate number for each",
    'home_address_label'                    => "Family's Actual Address (Division / District / Upazila)",
    'division_label'                          => 'Division',
    'district_field_label'                      => 'District',
    'upazila_label'                                => 'Upazila',
    'select_placeholder'                             => '— Select —',
    'zone_matched'                                     => 'This upazila falls under the "%s" relief zone.',
    'zone_not_covered'                                   => '⚠ There is no active relief operation in this upazila yet — registration is not possible.',
    'select_upazila_required'                              => 'Please select division, district, and upazila.',
    'register_btn'                          => 'Register',
    'registered_families_h2'                  => 'Registered Families',
    'admin_view_note'                           => 'Admin view — showing a hash preview (for demonstration only).',
    'operator_view_note'                          => '🔒 NGO Operator role cannot see the full list (privacy) — go to "Relief Distribution" and search by a specific NID.',
    'no_families_yet'                               => 'No families registered yet.',
    'th_name'                                          => 'Name',
    'th_members'                                         => 'Members',
    'nid_hash_preview'                                     => 'NID Hash (preview)',
    'fuzzy_modal_title'                                      => '⚠ Possible Duplicate Name Found',
    'cancel_btn'                                               => 'Cancel',
    'register_anyway_btn'                                        => 'Register anyway as new',
    'member_no'                                                    => 'Member',
    'name_placeholder'                                               => 'Name',
    'number_placeholder'                                               => 'Number',
    'birth_certificate'                                                  => 'Birth Certificate',
    'child_id_note'                                                        => "If the family head is a child, select Birth Certificate instead of NID.",

    'family_list_h2'          => '👪 All Registered Families',
    'family_list_sub'           => '{count} families are registered in total. New registrations will show up here on refresh.',
    'th_id'                        => 'ID',
    'th_phone'                       => 'Phone',
    'th_registered_at'                 => 'Registered At',

    'dup_log_sub'         => 'Whenever an NGO tries to give the same family relief in the same category a second time within 7 days, the system automatically blocks it and logs it here — for privacy, only the hash is stored, never the plain NID.',
    'dup_log_empty'         => 'No duplicate attempts have been blocked yet.',
    'th_attempted_ngo'        => 'NGO that attempted',
    'th_reason'                 => 'Reason',
    'audit_h2'                    => 'Lookup Audit Trail',
    'audit_sub'                     => 'Every lookup made while typing an NID on the "Relief Distribution" page — which NGO searched by which NID/Birth Certificate, and which family/member it resolved to.',
    'audit_empty'                     => 'No lookups yet.',
    'audit_resolved_to'                 => 'Resolved to',
    'audit_via_member'                    => 'matched via member',
    'audit_via_head'                        => "matched via head's NID",

    'ngo_reg_title'        => 'Foundation Registration — Relief Distribution System',
    'ngo_reg_h1'             => 'Foundation Registration',
    'ngo_reg_sub'              => 'Open a new NGO account with your official email',
    'ngo_reg_success'           => '✅ Registration successful! A 6-digit verification code has been sent to %s. Click the button below to enter it.',
    'enter_code_btn'              => 'Enter Code →',
    'ngo_name_label'              => 'Foundation/NGO Name',
    'reg_no_label'                  => 'Registration Number',
    'contact_phone_label'             => 'Contact Phone',
    'official_email_label'              => 'Official Email',
    'confirm_password_label'              => 'Password (re-type)',
    'reg_stock_label'                          => 'Initial Stock (Optional)',
    'reg_stock_sub'                              => 'Enter how much stock your organization currently has on hand — left blank counts as 0, and you can add more later from the "NGO Stock" page too.',
    'already_have_account'                  => 'Already have an account?',
    'err_required_fields'                     => 'Please fill in all required fields.',
    'err_bad_email'                             => 'Please enter a valid official email.',
    'err_password_length'                         => 'Password must be at least 6 characters.',
    'err_password_mismatch'                         => "Passwords don't match.",
    'err_ngo_exists'                                  => 'A foundation with this name, registration number, or email is already registered.',
    'err_user_exists'                                   => 'An account with this username or email already exists.',
    'err_registration_failed'                             => 'Registration failed. Please try again.',
    'err_mail_failed'                                       => 'Account created, but the verification email could not be sent: %s',

    'verify_title'        => 'Email Verification — Relief Distribution System',
    'verify_ok_h1'          => '✅ Verification Complete',
    'verify_ok_sub'           => 'Your account is now active. You can log in.',
    'go_to_login'               => 'Go to Login Page',
    'verify_expired_h1'           => '⌛ Code Expired',
    'verify_expired_sub'            => "This verification code has expired. Please register again — you'll get a new one.",
    'register_again'                  => 'Register Again',
    'verify_form_h1'                     => 'Enter Your Code',
    'verify_form_sub'                       => 'Enter the 6-digit verification code sent to your email.',
    'verify_code_label'                       => 'Verification Code',
    'verify_submit_btn'                         => 'Verify',
    'err_verify_invalid'                          => 'That email or code is incorrect (or already used). Please try again.',
    'verify_email_locked_note'                      => "The email used at registration is locked here — it can't be changed.",

    'api_family_required'   => 'NID, name, and upazila are required.',
    'api_member_count_mismatch' => "Everyone's info must be given, matching the family member count.",
    'api_member_fields_required' => "Each member's name, NID/Birth Certificate number, and type are required.",
    'api_family_saved'         => '"%s" and %d family member(s) were registered successfully.',
    'api_member_dup'             => "One member's NID/Birth Certificate number is already registered elsewhere.",
    'api_identity_conflict'         => 'This NID/Birth Certificate is already registered as "%s" under family_id #%d (as head or member) — the same person cannot be registered twice. If this is a mistake, correct the existing record instead.',
    'api_identity_conflict_db'        => 'This NID/Birth Certificate is already registered in another family (as head or member) — the database blocked it.',
    'api_save_failed'              => 'Save failed: %s',
    'api_dist_fields_required'       => 'Please fill in all fields.',
    'api_point_required'               => 'Point name and upazila are required.',
    'api_point_saved'                    => '"%s" was added successfully.',
    'api_csrf_invalid'                     => 'Your session expired or the form is stale — refresh the page and try again.',
    'api_session_expired'                    => 'Your session has expired — please log in again.',

    // ---- stock page ----
    'stock_h2'        => 'NGO Stock Management',
    'stock_sub'         => "See how much of each item every NGO currently has on hand. Stock is deducted automatically on every distribution — distribution is blocked once stock runs out.",
    'stock_empty'         => 'No stock records yet.',
    'stock_available'      => 'Current Stock',
    'stock_add'              => 'Add Stock',
    'stock_add_btn'            => 'Add',
    'stock_note'                => 'Every NGO-Item pair has one unique stock row. Pressing "Add" adds to the current amount, it does not replace it.',
    'stock_added_msg'             => '%s unit(s) of stock added.',

    // ---- profile page ----
    'profile_h2'                 => 'Profile',
    'profile_sub'                  => "View and update your organization's info and logo here.",
    'admin_profile_note'             => 'The admin account has no associated NGO, so profile customization does not apply.',
    'profile_change_photo'              => 'Change photo',
    'save_profile_btn'                    => 'Save',
    'profile_logo_note'                     => 'JPG, PNG, or WebP — max 2MB. Click the photo to pick a new logo, then press "Save".',
    'profile_saved_msg'                       => 'Profile updated successfully.',
    'err_logo_upload'                           => 'There was a problem uploading the photo. Please try again.',
    'err_logo_too_large'                          => 'The photo must be under 2MB.',
    'err_logo_type'                                 => 'Only JPG, PNG, or WebP images can be uploaded.',
],
];
